name: Merge Possible
on:
  pull_request:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
     #Container image has only the dependencies used installed
     image: nclsbayona/resume_on_markdown
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Delete old
        run: rm -rf generated
      - run: make

  auto-merge:
    name: Auto-merge dependabot pull request
    if: ${{ !(failure() || cancelled()) }}
    
    needs: 
     - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto-Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.0
        with:
          github-token: ${{ secrets.TOKEN }}
