name: Build Container Image

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
  schedule:
    - cron: "0 12 * * */30"
  workflow_dispatch:

env:
 IMAGE_NAME: resume_on_markdown
 USERNAME:  ${{ github.actor }}

concurrency:
  group: build-${{ github.event.push.number || github.ref }}
  cancel-in-progress: true

jobs:
  container_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and Push Versioned Docker Image
        id: build-and-push
        uses: docker/build-push-action@v2
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and Push Latest Docker Image
        id: build-and-push-latest
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
